---
output:
  pdf_document: default
  html_document: default
  word_document: default
---
```{r include = FALSE}
if(!knitr:::is_html_output())
{
  options("width"=56)
  knitr::opts_chunk$set(tidy.opts=list(width.cutoff=56, indent = 2), tidy = TRUE)
  #knitr::opts_chunk$set(fig.pos = 'h',  fig.align="center")
}
```
# Music 

## Climate Data as Inspiration
Students should look to the suggested climate data resources, or other reputable information, for inspiration to create a musical piece to be performed with their PVC instruments. Students should be allowed maximum creative freedom to interpret their data in musical form but some suggestions include converting wind speed changes into pitch variation, temperature into tempo, or spikes into percussion. Students should brainstorm and work among small teams to document their data source, their method of interpretation, and their data-to-music philosophy. 

### Documentation
Students may use letter-sized paper or posters to create a document, for public display, that describes their data set and music concept. Students should describe the data, what part(s) of it were used for inspiration, and how they imagined that data as sound. 

## Performance
Students will perform in small teams or pairs. A team leader should announce the piece and include a brief informative talk about the data source and how it was used to inspire the musical performance. Student performances should be brief -- perhaps 1-3 minutes. Creativity should be rewarded and students may be evaluated with regard to their integration of climate science, instrument construction, and concept development. Acknowledging that students are likely beginners at playing these instruments, students should not be assessed on their actual performance quality. This should be a fun exercise and is meant to inspire students to develop construction skills and foster interest in music and climate science.

Recordings of each performance may be made to document the results of the work. Recordings could be used for publication on social media if desired. 